version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run: mkdir -p artifacts
      - run:
          working_directory: ./MasterServer
          command: dotnet restore
      - run:
          working_directory: ./MasterServer
          command: dotnet publish -c Release -o ../artifacts --no-restore

      - persist_to_workspace:
          root: /artifacts
          paths:
            - ./*

  publish-github-release:
      docker:
        - image: cibuilds/github:0.13

      resource_class: small

      steps:
        - attach_workspace:
            at: ./artifacts

        - run:
            name: Package and push release
            command: |

              if [ "$CIRCLE_TAG" ]; then
                  tar czvf ./masterserver-{$CIRCLE_TAG}.gz ./artifacts/*

                  ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME \
                  -r $CIRCLE_PROJECT_REPONAME -n MasterServer-$CIRCLE_TAG --replace \
                  $CIRCLE_TAG masterserver-{$CIRCLE_TAG}.gz
              else
                echo "Missing CIRCLE_TAG env var!"
              fi

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: features/next
            tags:
              only: /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
