version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          working_directory: ./MasterServer
          command: dotnet restore
      - run:
          working_directory: ./MasterServer
          command: dotnet publish -c Release -o /tmp/artifacts --no-restore
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: feature/next