version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          working_directory: ./MasterServer
          command: dotnet restore
      - run:
          working_directory: ./MasterServer
          command: dotnet publish -c Release -o /tmp/artifacts --no-restore

      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - ./*

  publish-github-release:
      docker:
        - image: circleci/golang:1.9

      steps:
        - attach_workspace:
            at: /tmp/artifacts

        - run: go get -u github.com/tcnksm/ghr
        - run: go get -u github.com/stevenmatthewt/semantics

        - run:
            name: Package and push release
            working_directory: /tmp/artifacts
            command: |
              tag=$(semantics --output-tag)
              if [ "$tag" ]; then
                  tar -czvf masterserver-{$tag}.gz .

                  ghr -t $GITHUN_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag masterserver-{$tag}.gz
              else
                echo "The commit message(s) did not indicate a major/minor/patch version."
              fi

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: feature/next
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: feature/next